<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5ZCI5L2c5Yqg55uf');
$cfg_Cs[3]=array(0,17,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[4]=array(0,18,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[5]=array(4,18,1,'5aSa5p2G5pyI5a2j');
$cfg_Cs[6]=array(4,18,1,'55uG5pmv5pyI5a2j');
$cfg_Cs[7]=array(4,18,1,'5qCR54q25pyI5a2j');
$cfg_Cs[8]=array(4,18,1,'6YCg5Z6L5pyI5a2j');
$cfg_Cs[9]=array(4,18,1,'55u05p2G5pyI5a2j');
$cfg_Cs[10]=array(0,19,1,'5Yqg55uf5bqX6ZO6');
$cfg_Cs[11]=array(0,1,1,'6IGU57O75oiR5Lus');
?>