<div style="margin-bottom:15px;" class="inxinWen clearfix">
        <div class="inxinWenfl"> <a href="[field:arcurl/]"> <img src="[field:litpic/]">
          <h4>[field:title/]</h4>
          <p>    [field:description function="cn_substr(@me,110)"/]...</p>
          </a> </div>
        <div class="riqi"><span>[field:pubdate function="MyDate('Y-m',@me)"/]<br>
          <strong>[field:pubdate function="MyDate('d',@me)"/]</strong></span></div>
      </div>