<?php
$z[0]=Array("global","",1443,1475);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1616,1635);
$z[1][4]['name']="jmdh";
$z[2]=Array("global","",1746,1765);
$z[2][4]['name']="gsmc";
$z[3]=Array("global","",1918,1937);
$z[3][4]['name']="gsdz";
$z[4]=Array("global","",2364,2383);
$z[4][4]['name']="gscz";
$z[5]=Array("global","",3004,3036);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",3303,3322);
$z[6][4]['name']="gsdz";

?>