<?php
$z[0]=Array("include","",1433,1468);
$z[0][4]['filename']="ditu.htm";
$z[1]=Array("global","",1538,1557);
$z[1][4]['name']="jmdh";
$z[2]=Array("global","",1668,1687);
$z[2][4]['name']="gsmc";
$z[3]=Array("global","",1840,1859);
$z[3][4]['name']="gsdz";
$z[4]=Array("global","",2271,2290);
$z[4][4]['name']="gscz";
$z[5]=Array("global","",2898,2930);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",3197,3216);
$z[6][4]['name']="gsdz";

?>