<?php
$z[0]=Array("field","",129,148);
$z[0][4]['name']="title";
$z[1]=Array("global","",192,222);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",259,286);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",337,369);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",435,467);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",584,616);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",1361,1396);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",1457,1486);
$z[7][4]['name']="typename";
$z[8]=Array("field","",1502,1527);
$z[8][4]['name']="typenameen";
$z[9]=Array("channel","\r\n      <li><a href=\"[field:typelink/]\" > [field:typename/]</a></li>\r\n      ",1608,1737);
$z[9][4]['type']="son";
$z[9][4]['noself']="yes";
$z[10]=Array("list","\r\n    <li>\r\n      <div class=\"pic\"> <a href=\"[field:litpic/]\" title=\"[field:title/]\" rel=\"lightbox\"> <img src=\"[field:litpic/]\"> </a> </div>\r\n      <span>[field:title/]</span> </li>\r\n    ",1794,2032);
$z[10][4]['pagesize']="10";
$z[10][4]['titlelen']="60";
$z[11]=Array("pagelist","",2094,2160);
$z[11][4]['listitem']="index,end,pre,next,pageno";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",2201,2236);
$z[12][4]['filename']="foot.htm";

?>